### ISSUE TITLE
SSH Auth failed with generated SSH Key

### ISSUE THREAD

**Issue by Yamaha32088** [Ortus-Solutions/vagrant-ubuntu-lucee#3]
Thanks for this awesome Vagrant box! I had a little trouble getting it to work correctly the first go around because it would fail to authorize the SSH key. In the `Vagrant up` command it would say that it detected the insecure private key and then would regenerate a new one. However after it imported the new SSH key and try to authenticate it would always say that it failed. I was able to fix this by adding `config.ssh.insert_key = false` to the Vagrantfile and all seems to be working now. I am wondering if other people are running into this issue as well.

**Comment by bdw429s** [comment]
Hi @Yamaha32088 , I can't say I've seen that behavior before, but it's been a while since I've used this box so a newer version of Ubuntu might be causing it.  Actually, IIRC Ubuntu has been moving to stop using insecure hashes like SHA1 which might be the reason.  Can you send a pull for that config change?

**Comment by Yamaha32088** [comment]
I created a pull request.

**Comment by bdw429s** [comment]
Thanks for the pulls @Yamaha32088 !
